---
include:
  # Dongle (central) - plug this into USB, holds keymap, drives display
  - board: nice_nano//zmk
    shield: dongle

  # Left half (peripheral) - connects to dongle over BLE
  - board: nice_nano//zmk
    shield: lily58_left nice_view_adapter nice_view

  # Right half (peripheral) - connects to dongle over BLE
  - board: nice_nano//zmk
    shield: lily58_right nice_view_adapter nice_view

  # Wipe it all
  - board: nice_nano//zmk
    shield: settings_reset
