# ── Right Half — Peripheral Config ────────────────────────────────────────────
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_USB=n
CONFIG_LED=n

# ── Power saving ──────────────────────────────────────────────────────────────
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# ── Pointing ──────────────────────────────────────────────────────────────────
CONFIG_ZMK_POINTING=y
