# ── Right Half — Peripheral Config ────────────────────────────────────────────
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# REQUIRED: Must be 'y' to allow CONFIG_ZMK_USB_LOGGING to compile
CONFIG_ZMK_USB=y
CONFIG_LED=n

# ── Power saving ──────────────────────────────────────────────────────────────
# REQUIRED: Must be 'y' to utilize the sleep timeout value
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# ── Pointing ──────────────────────────────────────────────────────────────────
CONFIG_ZMK_POINTING=y

# ── Debugging ─────────────────────────────────────────────────────────────────
CONFIG_ZMK_USB_LOGGING=y
