# ── TEMPORARY DEBUG CONFIG ────────────────────────────────────────────────────
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y
# Temporarily make this a central so we can use USB
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_USB=y

# ── Pointing ──────────────────────────────────────────────────────────────────
CONFIG_ZMK_POINTING=y

# ── Debugging ─────────────────────────────────────────────────────────────────
CONFIG_ZMK_USB_LOGGING=y
